### ISSUE TITLE
[UI] SAML SLO response and request URLs are disable even when the single logout is enable

### ISSUE THREAD

**Issue by hasinidilanka** [wso2-extensions/identity-inbound-auth-saml#206]
**Description:**
When configuring new service provider using SAML configurations in the UI, by default single logout is enabled. But the two response and request urls are disable to edit. User need to first uncheck the checkbox for single logout option and then check again to edit urls.

**Suggested Labels:**
Bug

**Suggested Assignees:**
N/A

**Affected Product Version:**

WSO2IS-5.7.0 

**Steps to reproduce:**

1. Login to the Carbon Management Console.
2. Create a Service Provider.
3. Go to Inbound Authentication Configuration-> SAML2 Web SSO Configuration-> Configure
4. Try to add SLO response and request URLs under Enable Single Logout checkbox

**Related Issues:**

**Comment by deshankoswatte** [comment]
This is **fixed** in IS _5.10.0-M3_:

![Peek 2019-10-30 10-08](https://user-images.githubusercontent.com/33062368/67829475-59b1b880-fafd-11e9-9ed3-047697e42d4c.gif)

**Comment by GDRDABARERA** [comment]
Fixed in latest, hence closing
